using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PhotocopySystem.Data;
using PhotocopySystem.Models;
using System.Linq;

namespace PhotocopySystem.Controllers
{
    public class ProxyLogsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProxyLogsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // TODO for Awais: You are managing the Proxy Logs.
        // This tracks the network traffic of Students sending Print Jobs to the physical ServerNodes!

        // 1. Index() - GET (COMPLETED EXAMPLE)
        // What it does: Reads the ProxyLogs table from the database and displays it in a clean, read-only table ordered by Timestamp descending (newest first).
        public IActionResult Index()
        {
            // TODO: Once you finish the ProxyLog Model, uncomment the .Include line!
            var logs = _context.ProxyLogs
                /*.Include(p => p.ServerNode)*/
                .OrderByDescending(p => p.Timestamp)
                .ToList();
            return View(logs);
        }

        // No Create, Edit, or Delete methods! Logs are read-only and are generated by the Stored Procedures/Triggers.
    }
}
